- hosts: all
  tasks:

  #1. yum install httpd

  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest

#2. Systemctl start/enable httpd
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes
#3. Yum install wget unzip -y
  - name: install wget and unzip
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - unzip

#4. Wget  https://www.free-css.com/assets/files/free-css-templates/download/page286/plot-listing.zip

    
#5. Unzip templatemo_564_plot_listing
  - name: download and extract Template
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page286/plot-listing.zip
      dest: /tmp/
      remote_src: yes
#6. Cp -r templatemo_564_plot_listing/*   /var/www/html/

  - name: Copy file to var folder
    copy:
      src: /tmp/templatemo_564_plot_listing/
      remote_src: yes 
      dest: /var/www/html/